package com.lister.itms.dao.entity;

public class ProcessUserDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_process_user.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_process_user.user_id
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_process_user.process_role
     *
     * @mbggenerated
     */
    private String processRole;

    public ProcessUserDO() {
    }

    public ProcessUserDO(Long userId, String processRole) {
        this.userId = userId;
        this.processRole = processRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_process_user.id
     *
     * @return the value of sys_process_user.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_process_user.id
     *
     * @param id the value for sys_process_user.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_process_user.user_id
     *
     * @return the value of sys_process_user.user_id
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_process_user.user_id
     *
     * @param userId the value for sys_process_user.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_process_user.process_role
     *
     * @return the value of sys_process_user.process_role
     *
     * @mbggenerated
     */
    public String getProcessRole() {
        return processRole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_process_user.process_role
     *
     * @param processRole the value for sys_process_user.process_role
     *
     * @mbggenerated
     */
    public void setProcessRole(String processRole) {
        this.processRole = processRole == null ? null : processRole.trim();
    }
}
