package com.lister.itms.dao.entity;

import java.util.Date;

public class ProjectModuleDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itms_project_module.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itms_project_module.project_id
     *
     * @mbggenerated
     */
    private Long projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itms_project_module.module_name
     *
     * @mbggenerated
     */
    private String moduleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itms_project_module.module_desc
     *
     * @mbggenerated
     */
    private String moduleDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itms_project_module.is_deleted
     *
     * @mbggenerated
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itms_project_module.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itms_project_module.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itms_project_module.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itms_project_module.update_by
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itms_project_module.commons
     *
     * @mbggenerated
     */
    private String commons;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itms_project_module.id
     *
     * @return the value of itms_project_module.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itms_project_module.id
     *
     * @param id the value for itms_project_module.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itms_project_module.project_id
     *
     * @return the value of itms_project_module.project_id
     *
     * @mbggenerated
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itms_project_module.project_id
     *
     * @param projectId the value for itms_project_module.project_id
     *
     * @mbggenerated
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itms_project_module.module_name
     *
     * @return the value of itms_project_module.module_name
     *
     * @mbggenerated
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itms_project_module.module_name
     *
     * @param moduleName the value for itms_project_module.module_name
     *
     * @mbggenerated
     */
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName == null ? null : moduleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itms_project_module.module_desc
     *
     * @return the value of itms_project_module.module_desc
     *
     * @mbggenerated
     */
    public String getModuleDesc() {
        return moduleDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itms_project_module.module_desc
     *
     * @param moduleDesc the value for itms_project_module.module_desc
     *
     * @mbggenerated
     */
    public void setModuleDesc(String moduleDesc) {
        this.moduleDesc = moduleDesc == null ? null : moduleDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itms_project_module.is_deleted
     *
     * @return the value of itms_project_module.is_deleted
     *
     * @mbggenerated
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itms_project_module.is_deleted
     *
     * @param isDeleted the value for itms_project_module.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itms_project_module.create_time
     *
     * @return the value of itms_project_module.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itms_project_module.create_time
     *
     * @param createTime the value for itms_project_module.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itms_project_module.create_by
     *
     * @return the value of itms_project_module.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itms_project_module.create_by
     *
     * @param createBy the value for itms_project_module.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itms_project_module.update_time
     *
     * @return the value of itms_project_module.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itms_project_module.update_time
     *
     * @param updateTime the value for itms_project_module.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itms_project_module.update_by
     *
     * @return the value of itms_project_module.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itms_project_module.update_by
     *
     * @param updateBy the value for itms_project_module.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itms_project_module.commons
     *
     * @return the value of itms_project_module.commons
     *
     * @mbggenerated
     */
    public String getCommons() {
        return commons;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itms_project_module.commons
     *
     * @param commons the value for itms_project_module.commons
     *
     * @mbggenerated
     */
    public void setCommons(String commons) {
        this.commons = commons == null ? null : commons.trim();
    }
}
