package com.lister.itms.dao.entity;

public class SysConfigDO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.config_key
     *
     * @mbggenerated
     */
    private String configKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.config_value
     *
     * @mbggenerated
     */
    private String configValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.config_type
     *
     * @mbggenerated
     */
    private String configType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.state
     *
     * @mbggenerated
     */
    private String state;

    // 是否拥有
    private boolean isHave;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.id
     *
     * @return the value of sys_config.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.id
     *
     * @param id the value for sys_config.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.config_key
     *
     * @return the value of sys_config.config_key
     *
     * @mbggenerated
     */
    public String getConfigKey() {
        return configKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.config_key
     *
     * @param configKey the value for sys_config.config_key
     *
     * @mbggenerated
     */
    public void setConfigKey(String configKey) {
        this.configKey = configKey == null ? null : configKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.config_value
     *
     * @return the value of sys_config.config_value
     *
     * @mbggenerated
     */
    public String getConfigValue() {
        return configValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.config_value
     *
     * @param configValue the value for sys_config.config_value
     *
     * @mbggenerated
     */
    public void setConfigValue(String configValue) {
        this.configValue = configValue == null ? null : configValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.config_type
     *
     * @return the value of sys_config.config_type
     *
     * @mbggenerated
     */
    public String getConfigType() {
        return configType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.config_type
     *
     * @param configType the value for sys_config.config_type
     *
     * @mbggenerated
     */
    public void setConfigType(String configType) {
        this.configType = configType == null ? null : configType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.state
     *
     * @return the value of sys_config.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.state
     *
     * @param state the value for sys_config.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    public boolean isHave() {
        return isHave;
    }

    public void setHave(boolean have) {
        isHave = have;
    }
}
