package com.lister.itms.dao.mapper;

import com.github.pagehelper.Page;
import com.lister.itms.dao.entity.EnvironmentsDO;
import org.apache.ibatis.annotations.Param;


public interface EnvironmentsMapper {
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itms_environments
     *
     * @mbggenerated
     * @param environmentsDO
     */
    int deleteByPrimaryKey(EnvironmentsDO environmentsDO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itms_environments
     *
     * @mbggenerated
     */
    int insert(EnvironmentsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itms_environments
     *
     * @mbggenerated
     */
    int insertSelective(EnvironmentsDO record);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itms_environments
     *
     * @mbggenerated
     */
    EnvironmentsDO selectByPrimaryKey(Long id);

    /**
     *
     * @param environment
     * @param id
     * @return
     */
    int checkEnvironmentsExists(@Param("environment") String environment, @Param("id") Long id);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itms_environments
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EnvironmentsDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itms_environments
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EnvironmentsDO record);

    /**
     * 
     * @param environmentsDO
     * @return
     */
    Page<EnvironmentsDO> listPage(EnvironmentsDO environmentsDO);
    
}
