package com.lister.itms.dao.mapper;


import com.lister.itms.dao.entity.ProcessUserDO;

public interface ProcessUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_process_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_process_user
     *
     * @mbggenerated
     */
    int insert(ProcessUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_process_user
     *
     * @mbggenerated
     */
    int insertSelective(ProcessUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_process_user
     *
     * @mbggenerated
     */
    ProcessUserDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_process_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProcessUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_process_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProcessUserDO record);

    /**
     * 根据用户编号删除
     * @param userId
     */
    void deleteByUserId(Long userId);
}
