package com.lister.itms.dao.mapper;

import com.lister.itms.dao.entity.ProductUserDO;
import org.apache.ibatis.annotations.Param;

public interface ProductUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_product_user
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_product_user
     *
     * @mbggenerated
     */
    int insert(ProductUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_product_user
     *
     * @mbggenerated
     */
    int insertSelective(ProductUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_product_user
     *
     * @mbggenerated
     */
    ProductUserDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_product_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProductUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_product_user
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProductUserDO record);

    /**
     * 根据用户编号删除
     * @param userId
     */
    void deleteByUserId(@Param("userId") Long userId);
}
