package com.lister.itms.dao.mapper;

import com.github.pagehelper.Page;
import com.lister.itms.dao.entity.ProductDO;
import org.apache.ibatis.annotations.Param;

import java.util.List;


public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itms_product
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itms_product
     *
     * @mbggenerated
     */
    int insert(ProductDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itms_product
     *
     * @mbggenerated
     */
    int insertSelective(ProductDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itms_product
     *
     * @mbggenerated
     */
    ProductDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itms_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProductDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itms_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProductDO record);

    /**
     * 查询所有
     * @return
     * @param userId
     */
    List<ProductDO> listAll(@Param("userId") Long userId);

    /**
     * 检查产品名称是否已存在
     * @param productName
     * @param id
     * @return
     */
    int checkProductExists(@Param("productName") String productName, @Param("id") Long id);

    /**
     * 分页查询list
     * @param productDO
     * @return
     */
    Page<ProductDO> listPage(ProductDO productDO);
    

    /**
     * 根据项目编号查询所有产品，将关联上的产品的ishave设置为true
     * @param projectId
     * @return
     */
    List<ProductDO> getAllByProjectShowHave(@Param("projectId") Long projectId);
}
