package com.lister.itms.dao.mapper;

import com.github.pagehelper.Page;
import com.lister.itms.dao.entity.ProjectDO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itms_project
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itms_project
     *
     * @mbggenerated
     */
    int insert(ProjectDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itms_project
     *
     * @mbggenerated
     */
    int insertSelective(ProjectDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itms_project
     *
     * @mbggenerated
     */
    ProjectDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itms_project
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProjectDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itms_project
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProjectDO record);

    int checkProjectExists(@Param("projectName") String projectName, @Param("id") Long id);

    /**
     * 分页列表
     * @param projectDO
     * @return
     */
    Page<ProjectDO> listPage(ProjectDO projectDO);

    /**
     * 根据产品ID查询项目数量
     * @param id
     * @return
     */
    int getProjectCountByProduct(Long id);
}
