package com.lister.itms.dao.mapper;


import com.github.pagehelper.Page;
import com.lister.itms.dao.entity.ProjectVersionDO;

import java.util.List;

public interface ProjectVersionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itms_project_version
     *
     * @mbggenerated
     * @param projectVersionDO
     */
    int deleteByPrimaryKey(ProjectVersionDO projectVersionDO);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itms_project_version
     *
     * @mbggenerated
     */
    int insert(ProjectVersionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itms_project_version
     *
     * @mbggenerated
     */
    int insertSelective(ProjectVersionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itms_project_version
     *
     * @mbggenerated
     */
    ProjectVersionDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itms_project_version
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProjectVersionDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itms_project_version
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProjectVersionDO record);

    /**
     * 根据项目编号分页查询版本
     * @param projectVersionDO
     * @return
     */
    Page<ProjectVersionDO> listPage(ProjectVersionDO projectVersionDO);
    
    /**
     * 
     * @param projectVersionDO
     * @return
     */
    int checkExists(ProjectVersionDO projectVersionDO);
}
