package com.lister.itms.dao.mapper;

import com.github.pagehelper.Page;
import com.lister.itms.dao.entity.ProjectModuleDO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ProjectModuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itms_project_module
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(ProjectModuleDO projectModuleDO);   

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itms_project_module
     *
     * @mbggenerated
     */
    int insert(ProjectModuleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itms_project_module
     *
     * @mbggenerated
     */
    int insertSelective(ProjectModuleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itms_project_module
     *
     * @mbggenerated
     */
    ProjectModuleDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itms_project_module
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ProjectModuleDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table itms_project_module
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ProjectModuleDO record);

    /**
     * 
     * @param moduleName
     * @param id
     * @return
     */
    int checkProjectModuleExists(@Param("moduleName") String moduleName, @Param("id") Long id);

    /**
     * 
     * @param projectModuleDO
     * @return
     */
    Page<ProjectModuleDO> listPage(ProjectModuleDO projectModuleDO);
    
}
