package com.lister.itms.dao.mapper;

import com.lister.itms.dao.entity.SysConfigDO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbggenerated
     */
    int insert(SysConfigDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbggenerated
     */
    int insertSelective(SysConfigDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbggenerated
     */
    SysConfigDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysConfigDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysConfigDO record);

    /**
     * 根据类型获取配置
     * @param type
     * @return
     */
    List<SysConfigDO> getByType(String type);

    /**
     * 获取所以流程角色，并根据用户是否拥有角色而标识
     * @param userId
     * @return
     */
    List<SysConfigDO> getProcessRoleByUserId(@Param("userId") Long userId);
}
