package com.lister.itms.vo;

import java.util.Date;

public class ProjectVersionVo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itms_project_version.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itms_project_version.project_id
     *
     * @mbggenerated
     */
    private Long projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itms_project_version.version_name
     *
     * @mbggenerated
     */
    private String versionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itms_project_version.publish_date
     *
     * @mbggenerated
     */
    private Date publishDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itms_project_version.version_desc
     *
     * @mbggenerated
     */
    private String versionDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itms_project_version.state
     *
     * @mbggenerated
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itms_project_version.is_deleted
     *
     * @mbggenerated
     */
    private String isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itms_project_version.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itms_project_version.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itms_project_version.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itms_project_version.update_by
     *
     * @mbggenerated
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column itms_project_version.commons
     *
     * @mbggenerated
     */
    private String commons;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itms_project_version.id
     *
     * @return the value of itms_project_version.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itms_project_version.id
     *
     * @param id the value for itms_project_version.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itms_project_version.project_id
     *
     * @return the value of itms_project_version.project_id
     *
     * @mbggenerated
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itms_project_version.project_id
     *
     * @param projectId the value for itms_project_version.project_id
     *
     * @mbggenerated
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itms_project_version.version_name
     *
     * @return the value of itms_project_version.version_name
     *
     * @mbggenerated
     */
    public String getVersionName() {
        return versionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itms_project_version.version_name
     *
     * @param versionName the value for itms_project_version.version_name
     *
     * @mbggenerated
     */
    public void setVersionName(String versionName) {
        this.versionName = versionName == null ? null : versionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itms_project_version.publish_date
     *
     * @return the value of itms_project_version.publish_date
     *
     * @mbggenerated
     */
    public Date getPublishDate() {
        return publishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itms_project_version.publish_date
     *
     * @param publishDate the value for itms_project_version.publish_date
     *
     * @mbggenerated
     */
    public void setPublishDate(Date publishDate) {
        this.publishDate = publishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itms_project_version.version_desc
     *
     * @return the value of itms_project_version.version_desc
     *
     * @mbggenerated
     */
    public String getVersionDesc() {
        return versionDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itms_project_version.version_desc
     *
     * @param versionDesc the value for itms_project_version.version_desc
     *
     * @mbggenerated
     */
    public void setVersionDesc(String versionDesc) {
        this.versionDesc = versionDesc == null ? null : versionDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itms_project_version.state
     *
     * @return the value of itms_project_version.state
     *
     * @mbggenerated
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itms_project_version.state
     *
     * @param state the value for itms_project_version.state
     *
     * @mbggenerated
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itms_project_version.is_deleted
     *
     * @return the value of itms_project_version.is_deleted
     *
     * @mbggenerated
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itms_project_version.is_deleted
     *
     * @param isDeleted the value for itms_project_version.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itms_project_version.create_time
     *
     * @return the value of itms_project_version.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itms_project_version.create_time
     *
     * @param createTime the value for itms_project_version.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itms_project_version.create_by
     *
     * @return the value of itms_project_version.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itms_project_version.create_by
     *
     * @param createBy the value for itms_project_version.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itms_project_version.update_time
     *
     * @return the value of itms_project_version.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itms_project_version.update_time
     *
     * @param updateTime the value for itms_project_version.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itms_project_version.update_by
     *
     * @return the value of itms_project_version.update_by
     *
     * @mbggenerated
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itms_project_version.update_by
     *
     * @param updateBy the value for itms_project_version.update_by
     *
     * @mbggenerated
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column itms_project_version.commons
     *
     * @return the value of itms_project_version.commons
     *
     * @mbggenerated
     */
    public String getCommons() {
        return commons;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column itms_project_version.commons
     *
     * @param commons the value for itms_project_version.commons
     *
     * @mbggenerated
     */
    public void setCommons(String commons) {
        this.commons = commons == null ? null : commons.trim();
    }
}
